package enums;

//SNAPSHOT_FAIL 一天只能做一次库存盘点，第二次盘点返回snapshot_fail

public enum ResultMessage {
	SUCCESS,REMOTE_FAIL,ITEM_EXIST,ITEM_NOT_EXIST,IS_EMPTY,SAVE_FAIL,SNAPSHOT_FAIL,LOGIN_FAIL,NOT_LOGIN,
	DATE_ERROR,USER_NOT_EXIST,MESSAGE_NOT_EXIST,CANNOT_ADD,CANNOT_DELETE,CANNOT_UPDATE,NOT_MATCH,CLOSE,
	SAVE_SUCCESS, SUBMIT_SUCCESS, SAVE_FAILED, SUBMIT_FAIL;
}
